### PR TITLE
Changed Backgroud Color; Mentor profile page changes;

### PR DESCRIPTION
**Pull request by aniarya82**

### CODE REVIEW

**Comment by icyflame** [comment]
Please remove the script tag importing `bootstrap.min.js` from the
application layout file. It is already being included through the rails
asset pipeline.

**Comment by aniarya82** [comment]
Done. And also added a font family css tag

**Comment by icyflame** [comment]
@aniarya82 :+1: I will merge these changes later tonight.

**Comment by icyflame** [comment]
This PR was very good. Some feedback about this PR:
- Add the `gem pg` line to the Gemfile before initiating a PR. (This doesn't work on your machine but we need PG.)
- Keep the background image as banner.jpg for now. It is looking good. We can change it to a better image later.
- There is no need to show the details of the mentor who is signed in on the mentor profile page. We have to rather show the details of the Mentee, so that he remembers who they are and get's tempted to drop them an email or something.

**Comment by aniarya82** [comment]
I only added the details of mentor in the view for the looks purpose. And removing it and only keeping 2 columns kinda sucks. And also in mentee page we have three columns so its makes the website more alike. in mentor display page he can we the mentee appointed to him...

**Comment by aniarya82** [comment]
And please don't just change things back to what it was.
i changed the view with some purpose na.... and u again just reverted it back to the way it was....!!!!

**Comment by icyflame** [comment]
Hmm.. Okay! Sorry! We will meet and discuss about the design of the mentor
profile page.

On Sat, Feb 7, 2015 at 2:25 AM, Hiten Chowdhary notifications@github.com
wrote:

> And please don't just change things back to what it was.
> i changed the view with some purpose na.... and u again just reverted it
> back to the way it was....!!!!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/icyflame/mentorship-website-cum-portal/pull/16#issuecomment-73310571
> .

## 

Best Regards,

Siddharth Kannan,
Second Year, Undergraduate Student,
Mechanical Engineering Department,
Indian Institute of Technology,
Kharagpur,
West Bengal, India.
+91 9800190996.

**Pull request merged**
